format rice installer

diff --git a/bin/executable_rice b/bin/executable_rice
--- a/bin/executable_rice
+++ b/bin/executable_rice
@@ -18,15 +18,15 @@ Hint: No/empty command shows help."
     }
 
     case "$1" in
-        install|i)
-            install "$@"
-            ;;
-        docs|d)
-            docs "$@"
-            ;;
-        *)
-            cli_help
-            ;;
+    install | i)
+        install "$@"
+        ;;
+    docs | d)
+        docs "$@"
+        ;;
+    *)
+        cli_help
+        ;;
     esac
 }
 
@@ -55,96 +55,101 @@ Hint: No/empty command shows help."
     }
 
     case "$2" in
-        arch)
-            if hash yay 2>/dev/null; then
-                yay -Syu suckless-tools brave-bin notion-app alacritty zsh neofetch htop neovim code rsync rclone openssh go ttf-dejavu noto-fonts-emoji otf-overpass feh flameshot gpick xsel xcape dunst compton bat exa tmux screen ghostwriter
-            else
-                echo "Dependency \"yay\" not found."
-                exit 1
-            fi
-            ;;
-        code)
-            code --install-extension "naumovs.color-highlight"
-            code --install-extension "editorconfig.editorconfig"
-            code --install-extension "lokalise.i18n-ally"
-            code --install-extension "tinkertrain.theme-panda"
-            code --install-extension "dominicvonk.parameter-hints"
-            code --install-extension "ionutvmi.path-autocomplete"
-            code --install-extension "esbenp.prettier-vscode"
-            code --install-extension "ow.vscode-subword-navigation"
-            code --install-extension "redhat.vscode-yaml"
-            ;;
-        code-optional)
-            code --install-extension "bierner.emojisense"
-            code --install-extension "ms-azuretools.vscode-docker"
-            code --install-extension "dbaeumer.vscode-eslint"
-            code --install-extension "eamodio.gitlens"
-            code --install-extension "mkaufman.htmlhint"
-            code --install-extension "wix.vscode-import-cost"
-            code --install-extension "bierner.markdown-preview-github-styles"
-            code --install-extension "silvenon.mdx"
-            code --install-extension "ryu1kn.partial-diff"
-            code --install-extension "richie5um2.vscode-sort-json"
-            code --install-extension "simonsiefke.svg-preview"
-            code --install-extension "pflannery.vscode-versionlens"
-            code --install-extension "alfnielsen.vsc-rename-files"
-            code --install-extension "antfu.browse-lite"
-            ;;
-        code-languages)
-            code --install-extension "heybourn.headwind"
-            code --install-extension "fivethree.vscode-svelte-snippets"
-            code --install-extension "svelte.svelte-vscode"
-            code --install-extension "bradlc.vscode-tailwindcss"
-            code --install-extension "voorjaar.windicss-intellisense"
-            code --install-extension "stylelint.vscode-stylelint"
-            code --install-extension "octref.vetur"
-            code --install-extension "timonwong.shellcheck"
-            ;;
-        deb)
-            if hash aptitude 2>/dev/null; then
-                echo "installing aptitude"
-                sudo apt install aptitude
-            elif hash apt 2>/dev/null; then
-                echo "installing aptitude"
+    arch)
+        if hash yay 2>/dev/null; then
+            yay -Syu suckless-tools brave-bin notion-app alacritty zsh neofetch htop neovim code rsync rclone openssh go ttf-dejavu noto-fonts-emoji otf-overpass feh flameshot gpick xsel xcape dunst compton bat exa tmux screen ghostwriter
+        else
+            echo "Dependency \"yay\" not found."
+            exit 1
+        fi
+        ;;
+    code)
+        code --install-extension "naumovs.color-highlight"
+        code --install-extension "editorconfig.editorconfig"
+        code --install-extension "lokalise.i18n-ally"
+        code --install-extension "tinkertrain.theme-panda"
+        code --install-extension "dominicvonk.parameter-hints"
+        code --install-extension "ionutvmi.path-autocomplete"
+        code --install-extension "esbenp.prettier-vscode"
+        code --install-extension "ow.vscode-subword-navigation"
+        code --install-extension "redhat.vscode-yaml"
+        ;;
+    code-optional)
+        code --install-extension "bierner.emojisense"
+        code --install-extension "ms-azuretools.vscode-docker"
+        code --install-extension "dbaeumer.vscode-eslint"
+        code --install-extension "eamodio.gitlens"
+        code --install-extension "mkaufman.htmlhint"
+        code --install-extension "wix.vscode-import-cost"
+        code --install-extension "bierner.markdown-preview-github-styles"
+        code --install-extension "silvenon.mdx"
+        code --install-extension "ryu1kn.partial-diff"
+        code --install-extension "richie5um2.vscode-sort-json"
+        code --install-extension "simonsiefke.svg-preview"
+        code --install-extension "pflannery.vscode-versionlens"
+        code --install-extension "alfnielsen.vsc-rename-files"
+        code --install-extension "antfu.browse-lite"
+        ;;
+    code-languages)
+        code --install-extension "stylelint.vscode-stylelint"
 
-                sudo aptitude install alacritty screen tmux flameshot ghostwriter
-            else
-                echo "Dependency \"apt\" not found."
-                exit 1
-            fi
-            ;;
-        dwm)
-            cd ~/.local/src/dwm && git pull && sudo make clean install
-            ;;
-        fzf)
-            chmod +x ~/.local/src/fzf/install
-            ~/.local/src/fzf/install --bin
-            ;;
-        go)
-            go get -u github.com/cosmtrek/air github.com/nektos/act github.com/xxxserxxx/gotop/cmd/gotop github.com/yudai/gotty
-            ;;
-        golang)
-            sudo rm -rf /usr/local/go
-            if [ "$3" ]; then
-                GO_VERSION="go$3"
-            else
-                GO_VERSION=$(curl -s "https://golang.org/VERSION?m=text")
-            fi
-            curl --progress-bar "https://dl.google.com/go/$GO_VERSION.linux-amd64.tar.gz" | sudo tar zxf - -C /usr/local
-            go version
-            ;;
-        npm)
-            npm i -g pnpm np doctoc prettier js-beautify tinypng-cli diff-so-fancy npm-check-updates sirv-cli live-server firebase-tools markdownlint-cli semver bundle-phobia-cli imagemin imagemin-webp
-            ;;
-        volta)
-            curl https://get.volta.sh | bash -s -- "--skip-setup"
-            ;;
-        zsh)
-            cloneZshModule https://github.com/MichaelAquilina/zsh-you-should-use.git https://github.com/zsh-users/zsh-syntax-highlighting.git https://github.com/sindresorhus/pure.git
-            ;;
-        *)
-            cli_help_packages
-            ;;
+        code --install-extension "fivethree.vscode-svelte-snippets"
+        code --install-extension "svelte.svelte-vscode"
+
+        code --install-extension "octref.vetur"
+
+        code --install-extension "heybourn.headwind"
+        code --install-extension "bradlc.vscode-tailwindcss"
+        code --install-extension "voorjaar.windicss-intellisense"
+
+        code --install-extension "timonwong.shellcheck"
+        code --install-extension "foxundermoon.shell-format"
+        ;;
+    deb)
+        if hash aptitude 2>/dev/null; then
+            echo "installing aptitude"
+            sudo apt install aptitude
+        elif hash apt 2>/dev/null; then
+            echo "installing aptitude"
+
+            sudo aptitude install alacritty screen tmux flameshot ghostwriter
+        else
+            echo "Dependency \"apt\" not found."
+            exit 1
+        fi
+        ;;
+    dwm)
+        cd ~/.local/src/dwm && git pull && sudo make clean install
+        ;;
+    fzf)
+        chmod +x ~/.local/src/fzf/install
+        ~/.local/src/fzf/install --bin
+        ;;
+    go)
+        go get -u github.com/cosmtrek/air github.com/nektos/act github.com/xxxserxxx/gotop/cmd/gotop github.com/yudai/gotty
+        ;;
+    golang)
+        sudo rm -rf /usr/local/go
+        if [ "$3" ]; then
+            GO_VERSION="go$3"
+        else
+            GO_VERSION=$(curl -s "https://golang.org/VERSION?m=text")
+        fi
+        curl --progress-bar "https://dl.google.com/go/$GO_VERSION.linux-amd64.tar.gz" | sudo tar zxf - -C /usr/local
+        go version
+        ;;
+    npm)
+        npm i -g pnpm np doctoc prettier js-beautify tinypng-cli diff-so-fancy npm-check-updates sirv-cli live-server firebase-tools markdownlint-cli semver bundle-phobia-cli imagemin imagemin-webp
+        ;;
+    volta)
+        curl https://get.volta.sh | bash -s -- "--skip-setup"
+        ;;
+    zsh)
+        cloneZshModule https://github.com/MichaelAquilina/zsh-you-should-use.git https://github.com/zsh-users/zsh-syntax-highlighting.git https://github.com/sindresorhus/pure.git
+        ;;
+    *)
+        cli_help_packages
+        ;;
     esac
 }
 
@@ -159,19 +164,19 @@ Usage: $cli_name docs git|posix|shortcuts|units|vim"
 
     BASE_CHEZMOI="$(chezmoi source-path)/src/docs/"
     case "$2" in
-        git|posix|shortcuts|units|vim)
-            less "$BASE_CHEZMOI/$2.md"
-            ;;
-        *)
-            cli_help_docs
-            ;;
+    git | posix | shortcuts | units | vim)
+        less "$BASE_CHEZMOI/$2.md"
+        ;;
+    *)
+        cli_help_docs
+        ;;
     esac
 }
 
 cloneZshModule() {
     cd "$ZSHPATH" || exit
     for n in "$@"; do
-        git clone "$n" 2> /dev/null
+        git clone "$n" 2>/dev/null
     done
 }
 
